substitutions:
  _REGION: us-central1
  _WEB_SERVICE: agenttown-web
  _WS_SERVICE: agenttown-ws
  _ENV_KEYS_FILE: scripts/gcp/cloud-run-env.keys
  _SECRET_VERSION: latest

steps:
  - name: gcr.io/cloud-builders/docker
    secretEnv:
      - NEXT_PUBLIC_AI_ENABLED
      - NEXT_PUBLIC_SIM_LOG_LEVEL
      - NEXT_PUBLIC_WS_URL
    args:
      [
        "build",
        "-f",
        "Dockerfile",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/agenttown/agenttown-web:latest",
        "--build-arg",
        "NEXT_PUBLIC_AI_ENABLED=$$NEXT_PUBLIC_AI_ENABLED",
        "--build-arg",
        "NEXT_PUBLIC_SIM_LOG_LEVEL=$$NEXT_PUBLIC_SIM_LOG_LEVEL",
        "--build-arg",
        "NEXT_PUBLIC_WS_URL=$$NEXT_PUBLIC_WS_URL",
        ".",
      ]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/agenttown/agenttown-web:latest"]

  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "Dockerfile.ws", "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/agenttown/agenttown-ws:latest", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/agenttown/agenttown-ws:latest"]

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -ceu
      - |
        SECRET_MAPPINGS="$(./scripts/gcp/render-cloud-run-secrets.sh --keys-file "${_ENV_KEYS_FILE}" --version "${_SECRET_VERSION}")"
        gcloud run deploy "${_WEB_SERVICE}" \
          --image "${_REGION}-docker.pkg.dev/$PROJECT_ID/agenttown/agenttown-web:latest" \
          --region "${_REGION}" \
          --allow-unauthenticated \
          --clear-env-vars \
          --set-secrets "$$SECRET_MAPPINGS"

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -ceu
      - |
        SECRET_MAPPINGS="$(./scripts/gcp/render-cloud-run-secrets.sh --keys-file "${_ENV_KEYS_FILE}" --version "${_SECRET_VERSION}")"
        gcloud run deploy "${_WS_SERVICE}" \
          --image "${_REGION}-docker.pkg.dev/$PROJECT_ID/agenttown/agenttown-ws:latest" \
          --region "${_REGION}" \
          --allow-unauthenticated \
          --clear-env-vars \
          --set-secrets "$$SECRET_MAPPINGS"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/agenttown/agenttown-web:latest"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/agenttown/agenttown-ws:latest"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_AI_ENABLED/versions/${_SECRET_VERSION}
      env: NEXT_PUBLIC_AI_ENABLED
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_SIM_LOG_LEVEL/versions/${_SECRET_VERSION}
      env: NEXT_PUBLIC_SIM_LOG_LEVEL
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_WS_URL/versions/${_SECRET_VERSION}
      env: NEXT_PUBLIC_WS_URL
