CREATE TABLE IF NOT EXISTS agent_reasonings (
  agent_id VARCHAR(64) PRIMARY KEY,
  why TEXT NOT NULL,
  memory_refs JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sim_events (
  id VARCHAR(64) PRIMARY KEY,
  tick INT NOT NULL,
  type VARCHAR(32) NOT NULL,
  actors JSON NULL,
  at_x INT NULL,
  at_y INT NULL,
  message TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sim_metrics (
  tick INT PRIMARY KEY,
  confusion INT NOT NULL,
  rumor_spread INT NOT NULL,
  official_reach INT NOT NULL,
  vulnerable_reach INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agent_memories (
  id VARCHAR(64) PRIMARY KEY,
  agent_id VARCHAR(64) NOT NULL,
  content TEXT NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  event_id VARCHAR(64) NULL,
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
